name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    timeout-minutes: 5

    strategy:
      matrix:
        arch: ['src64']
        version: ['17.12', '18.6', '18.12', '19.6', 'latest']
        ansible: ['1.8.4', '2.7']

    steps:
      - uses: actions/checkout@v1
      - uses: aw/picolisp-action@v1
        with:
          version: ${{matrix.version}}
          architecture: ${{matrix.arch}}

      - name: Install Ansible (old version)
        run: sudo pip install ansible==${{matrix.ansible}}

      - name: Run the tests on PicoLisp ${{matrix.arch}} v${{matrix.version}} with Ansible v${{matrix.ansible}}
        run: make check
